name: open-project

services:
  db-dev:
    image: postgres:18-alpine
    container_name: open-project-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-thisisapassword}
      POSTGRES_DB: ${DATABASE_DB:-open_project}
    volumes:
      - db-dev-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_DB:-open_project}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - db-dev-network

  db-client-dev:
    image: t8y2/dbx:latest
    container_name: open-project-db-client-dev
    pull_policy: always
    restart: always
    ports:
      - "4224:4224"
    volumes:
      - db-client-dev-data:/app/data
    depends_on:
      db-dev:
        condition: service_healthy
    networks:
      - db-dev-network

  api-dev:
    container_name: open-project-api-dev
    build:
      context: ../api
      dockerfile: dockerfile
    env_file:
      - ../api/.env
    ports:
      - "8000:80"
    depends_on:
      db-dev:
        condition: service_healthy
    command:
      [
        "/opt/venv/bin/fastapi",
        "dev",
        "/app/src/main.py",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
      ]
    volumes:
      - ../api/src:/app/src
      - ../api/alembic:/app/alembic
    networks:
      - db-dev-network
      - api-dev-network

  web-dev:
    container_name: open-project-web-dev
    env_file:
      - ../web/.env
    build:
      context: ../web
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../web/src:/app/src
    networks:
      - api-dev-network
    command: ["pn", "dev", "--host", "0.0.0.0"]

volumes:
  db-dev-data:
  db-client-dev-data:

networks:
  db-dev-network:
  api-dev-network:
